from typing import Iterator, Protocol, runtime_checkable


@runtime_checkable
class PathLike(Protocol):
    """Protocol defining the path operations required by the controller."""

    @property
    def suffix(self) -> str: ...

    @property
    def stem(self) -> str: ...

    @property
    def name(self) -> str: ...

    def exists(self) -> bool: ...

    def is_dir(self) -> bool: ...

    def iterdir(self) -> Iterator["PathLike"]: ...

    def with_suffix(self, suffix: str) -> "PathLike": ...

    def with_name(self, name: str) -> "PathLike": ...

    def stat(self) -> object: ...

    def __truediv__(self, other: str) -> "PathLike": ...